export let products = [
  {
    id: 1,
    title: "JavaScript",
    price: 345000,
    stock: 5,
    description: "Lenguaje de programacion",
    detalle: `"JavaScript es un lenguaje de programación interpretado, dialecto del estándar ECMAScript. Se define como orientado a objetos, 
    basado en prototipos, imperativo, débilmente tipado y dinámico."`,
    duracion: "2 años",
    category: "carrera",
    img: "https://res.cloudinary.com/dheurnsr0/image/upload/v1697503733/JavaScritp_sal8cc.jpg",
  },
  {
    id: 2,
    title: "Angular",
    price: 325000,
    stock: 5,
    description: "Framework para aplicaiones",
    detalle: `"Angular es un framework para aplicaciones web desarrollado en TypeScript, de código abierto, 
    mantenido por Google, que se utiliza para crear y mantener aplicaciones web de una sola página."`,
    duracion: "4 meses",
    category: "curso",
    img: "https://res.cloudinary.com/dheurnsr0/image/upload/v1697503728/angulas_js_oqbhrx.jpg",
  },
  {
    id: 3,
    title: "React Js",
    price: 230000,
    stock: 5,
    description: "Libreria de JavaScript",
    detalle: `"React es una librería Javascript de código abierto diseñada para crear interfaces
    de usuario con el objetivo de facilitar el desarrollo de aplicaciones en una sola página."`,
    duracion: "6 meses",
    category: "curso",
    img: "https://res.cloudinary.com/dheurnsr0/image/upload/v1697503729/react_eex4np.jpg",
  },
  {
    id: 4,
    title: "HTML5",
    price: 180000,
    stock: 5,
    description: "Lenguaje de marcado",
    detalle: `"HTML, siglas en inglés de HyperText Markup Language, 
    hace referencia al lenguaje de marcado para la elaboración de páginas web."`,
    duracion: "1 año",
    category: "carrera",
    img: "https://res.cloudinary.com/dheurnsr0/image/upload/v1697503731/html_gdouu1.jpg",
  },
];
