export let products = [
  {
    id: 1,
    title: "Promo 1",
    price: 1770,
    stock: 5,
    description: "Fiambreria",
    detalle: `"JavaScript es un lenguaje de programación interpretado, dialecto del estándar ECMAScript. Se define como orientado a objetos, 
    basado en prototipos, imperativo, débilmente tipado y dinámico."`,
    duracion: "En stock",
    category: "promociones",
    img: "https://res.cloudinary.com/dheurnsr0/image/upload/v1699399301/promo_1_pp656g.png",
  },
  {
    id: 2,
    title: "Promo 2",
    price: 1530,
    stock: 5,
    description: "Fiambreria",
    detalle: `"Angular es un framework para aplicaciones web desarrollado en TypeScript, de código abierto, 
    mantenido por Google, que se utiliza para crear y mantener aplicaciones web de una sola página."`,
    duracion: "En stock",
    category: "promociones",
    img: "https://res.cloudinary.com/dheurnsr0/image/upload/v1699399301/promo_2_zzhdsm.png",
  },
  {
    id: 3,
    title: "Promo 3",
    price: 2830,
    stock: 5,
    description: "Fiambreria",
    detalle: `"React es una librería Javascript de código abierto diseñada para crear interfaces
    de usuario con el objetivo de facilitar el desarrollo de aplicaciones en una sola página."`,
    duracion: "En stock",
    category: "promociones",
    img: "https://res.cloudinary.com/dheurnsr0/image/upload/v1699399301/promo_3_bctdxs.png",
  },
  {
    id: 4,
    title: "Promo 4",
    price: 1650,
    stock: 5,
    description: "Fiambreria",
    detalle: `"HTML, siglas en inglés de HyperText Markup Language, 
    hace referencia al lenguaje de marcado para la elaboración de páginas web."`,
    duracion: "En stock",
    category: "promociones",
    img: "https://res.cloudinary.com/dheurnsr0/image/upload/v1699399301/promo_4_ybttre.png",
  },
  {
    id: 5,
    title: "Promo 5",
    price: 1620,
    stock: 5,
    description: "Fiambreria",
    detalle: `"HTML, siglas en inglés de HyperText Markup Language, 
    hace referencia al lenguaje de marcado para la elaboración de páginas web."`,
    duracion: "En stock",
    category: "promociones",
    img: "https://res.cloudinary.com/dheurnsr0/image/upload/v1699399301/promo_5_hpvg1b.png",
  },
  {
    id: 6,
    title: "Promo 6",
    price: 1070,
    stock: 5,
    description: "Fiambreria",
    detalle: `"HTML, siglas en inglés de HyperText Markup Language, 
    hace referencia al lenguaje de marcado para la elaboración de páginas web."`,
    duracion: "En stock",
    category: "promociones",
    img: "https://res.cloudinary.com/dheurnsr0/image/upload/v1699399302/promo_6_r9o6iq.png",
  },
  {
    id: 7,
    title: "Promo 7",
    price: 1680,
    stock: 5,
    description: "Fiambreria",
    detalle: `"HTML, siglas en inglés de HyperText Markup Language, 
    hace referencia al lenguaje de marcado para la elaboración de páginas web."`,
    duracion: "En stock",
    category: "promociones",
    img: "https://res.cloudinary.com/dheurnsr0/image/upload/v1699399300/promo_7_xwtotg.png",
  },
  {
    id: 8,
    title: "Promo 8",
    price: 999,
    stock: 5,
    description: "Fiambreria",
    detalle: `"HTML, siglas en inglés de HyperText Markup Language, 
    hace referencia al lenguaje de marcado para la elaboración de páginas web."`,
    duracion: "En stock",
    category: "promociones",
    img: "https://res.cloudinary.com/dheurnsr0/image/upload/v1699399300/promo_8_hrrbq1.png",
  },
  {
    id: 9,
    title: "Maple de huevo",
    price: 1900,
    stock: 5,
    description: "30 huevos N2",
    detalle: `"HTML, siglas en inglés de HyperText Markup Language, 
    hace referencia al lenguaje de marcado para la elaboración de páginas web."`,
    duracion: "En stock",
    category: "granja",
    img: "https://res.cloudinary.com/dheurnsr0/image/upload/v1699399302/maple_dkozju.png",
  },
  {
    id: 10,
    title: "Milanesa de pollo",
    price: 2200,
    stock: 5,
    description: "rebozadas de pollo",
    detalle: `"HTML, siglas en inglés de HyperText Markup Language, 
    hace referencia al lenguaje de marcado para la elaboración de páginas web."`,
    duracion: "En stock",
    category: "granja",
    img: "https://res.cloudinary.com/dheurnsr0/image/upload/v1699399300/milanesa_de_polllo_ugd6oq.png",
  },
];
