export let products = [
  {
    id: 1,
    title: "Promo 1",
    price: 1770,
    stock: 5,
    description: "Fiambreria",
    detalle: `" * 250gr de queso de maquina
    *250gr de Salame "`,
    duracion: "En stock",
    category: "promociones",
    img: "https://res.cloudinary.com/dheurnsr0/image/upload/v1699399301/promo_1_pp656g.png",
  },
  {
    id: 2,
    title: "Promo 2",
    price: 1530,
    stock: 5,
    description: "Fiambreria",
    detalle: `" * 250gr de queso de maquina
    *250gr de Paleta "`,
    duracion: "En stock",
    category: "promociones",
    img: "https://res.cloudinary.com/dheurnsr0/image/upload/v1699399301/promo_2_zzhdsm.png",
  },
  {
    id: 3,
    title: "Promo 3",
    price: 2830,
    stock: 5,
    description: "Fiambreria",
    detalle: `" * 250gr de Jamon Cocido
    *150gr de Bondiola *150gr de Queso de Maquina "`,
    duracion: "En stock",
    category: "promociones",
    img: "https://res.cloudinary.com/dheurnsr0/image/upload/v1699399301/promo_3_bctdxs.png",
  },
  {
    id: 4,
    title: "Promo 4",
    price: 1650,
    stock: 5,
    description: "Fiambreria",
    detalle: `" * 150gr de Jamon Cocido
    *150gr de Mortadela *150gr de Queso de Maquina "`,
    duracion: "En stock",
    category: "promociones",
    img: "https://res.cloudinary.com/dheurnsr0/image/upload/v1699399301/promo_4_ybttre.png",
  },
  {
    id: 5,
    title: "Promo 5",
    price: 1620,
    stock: 5,
    description: "Fiambreria",
    detalle: `" * 150gr de Jamon Cocido
    *150gr de Jamon Crudo"`,
    duracion: "En stock",
    category: "promociones",
    img: "https://res.cloudinary.com/dheurnsr0/image/upload/v1699399301/promo_5_hpvg1b.png",
  },
  {
    id: 6,
    title: "Promo 6",
    price: 1070,
    stock: 5,
    description: "Fiambreria",
    detalle: `" * 150gr de Queso de Maquina
    *150gr de Matambre"`,
    duracion: "En stock",
    category: "promociones",
    img: "https://res.cloudinary.com/dheurnsr0/image/upload/v1699399302/promo_6_r9o6iq.png",
  },
  {
    id: 7,
    title: "Promo 7",
    price: 1680,
    stock: 5,
    description: "Fiambreria",
    detalle: `" * 250gr de Jamon Cocido
    *250gr de Queso de Maquina"`,
    duracion: "En stock",
    category: "promociones",
    img: "https://res.cloudinary.com/dheurnsr0/image/upload/v1699399300/promo_7_xwtotg.png",
  },
  {
    id: 8,
    title: "Promo 8",
    price: 999,
    stock: 5,
    description: "Fiambreria",
    detalle: `"250gr de Jamon Cocido Il Molise"`,
    duracion: "En stock",
    category: "promociones",
    img: "https://res.cloudinary.com/dheurnsr0/image/upload/v1699399300/promo_8_hrrbq1.png",
  },
  {
    id: 9,
    title: "Maple de huevo",
    price: 1900,
    stock: 5,
    description: "30 huevos N2",
    detalle: `"Huevos Blancos por Maple."`,
    duracion: "En stock",
    category: "granja",
    img: "https://res.cloudinary.com/dheurnsr0/image/upload/v1699399302/maple_dkozju.png",
  },
  {
    id: 10,
    title: "Milanesa de pollo",
    price: 2200,
    stock: 5,
    description: "rebozadas de pollo",
    detalle: `"Suprema rebozada con provenzal y pan rallado."`,
    duracion: "En stock",
    category: "granja",
    img: "https://res.cloudinary.com/dheurnsr0/image/upload/v1699399300/milanesa_de_polllo_ugd6oq.png",
  },
  {
    id: 11,
    title: "Pata y Muslo",
    price: 2200,
    stock: 5,
    description: "Cuarto trasero de pollo",
    detalle: `"La Pata y Muslo de Pollo son un conjunto seleccionado de la parte trasera del pollo,
     formando una sola pieza tierna y jugosa. "`,
    duracion: "En stock",
    category: "granja",
    img: "https://res.cloudinary.com/dheurnsr0/image/upload/v1699446980/pata_muslo_wl6hdk.png",
  },
  {
    id: 12,
    title: "Medallones de pollo",
    price: 1900,
    stock: 5,
    description: "rebozadas de pollo",
    detalle: `"Carne de Pollo, Agua, Pan Rallado, Almidón de Trigo, 
    Espesante (Harina de Trigo Modificada, Almidón de Trigo, Sal y Carboximetilcelulosa)."`,
    duracion: "En stock",
    category: "granja",
    img: "https://res.cloudinary.com/dheurnsr0/image/upload/v1699447450/medallones_de_pollo_fvrhhe.png",
  },
  {
    id: 13,
    title: "Azucar Ledezma",
    price: 999,
    stock: 5,
    description: "Producto Endulzante",
    detalle: `"Valor Nutricional por cucharada 5gr (1 cucharada de té)
    Energía: 20Kcal
    Que están formadas por:
    Hidratos de carbono: 5gr
    Proteínas:0g
    Grasas:0g"`,
    duracion: "En stock",
    category: "almacen",
    img: "https://res.cloudinary.com/dheurnsr0/image/upload/v1699447650/azucar-ledesma-bolsa-de-1kg-_d6tvsl.jpg",
  },
  {
    id: 14,
    title: "Arroz Lucchetti",
    price: 900,
    stock: 5,
    description: "Arroz tipo Parboil",
    detalle: `"Valores Diarios con base a una dieta de 2.000 kcal u 8.400 kJ. 
    Sus valores diarios pueden ser mayores o menores dependiendo de sus necesidades energéticas"`,
    duracion: "En stock",
    category: "almacen",
    img: "https://res.cloudinary.com/dheurnsr0/image/upload/v1699447885/81-4-2_akogel.png",
  },
  {
    id: 15,
    title: "Mostachol Lucchetti",
    price: 950,
    stock: 5,
    description: "Fideos de tipo Mostachol",
    detalle: `"sémola de trigo, espinaca deshidratada, zanahoria en polvo, zapallo en polvo, vitamina B2, 
    vitamina B6, vitamina B1, vitamina A, vitamina B9, vitamina D, vitamina B12."`,
    duracion: "En stock",
    category: "almacen",
    img: "https://res.cloudinary.com/dheurnsr0/image/upload/v1699447950/7790070335531_02_lr23ry.jpg",
  },
  {
    id: 16,
    title: "Yerba Playadito 1kg",
    price: 2200,
    stock: 5,
    description: "Yerba Mate",
    detalle: `"Playadito está elaborada con palo y libre de gluten, se caracteriza por su delicioso sabor suave."`,
    duracion: "En stock",
    category: "almacen",
    img: "https://res.cloudinary.com/dheurnsr0/image/upload/v1699448060/Yerba-Mate-Playadito-Suave-X1kg-1-854539_rgthhu.jpg",
  },
];
